name: Check FIT Image Metadata

on:
  pull_request:

jobs:
  check-fitimage:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y device-tree-compiler

      - name: Make script executable
        run: chmod +x ./check-fitimage-metadata.sh

      - name: Run FIT image metadata check
        run: ./check-fitimage-metadata.sh
